allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
catalog:
  rolldown: "^1.1.1"
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1
minimumReleaseAgeExclude:
  - "@vizejs/*"
  - vize
  - "@typescript/native-preview"
  - "@typescript/native-preview-*"
  - rolldown
  - "@rolldown/*"
  - "@voidzero-dev/vite-plus-*"
  - vite-plus
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
